#Example configuration.yaml
## Describes the format for available dahua_event:
#
dahua_event:
#
  - name: Laundry
    protocol: http
    host: !secret laundry_cam_ip
    port: 80
    user: !secret nvr_username
    password: !secret nvr_passsword
    events:
      - CrossLineDetection
      - CrossRegionDetection
      - LeftDetection
      - TakenAwayDetection
      - FaceDetection
      - AudioMutation
      - AudioAnomaly
    channels:
      - number: 1
        name: Laundromat
#
  - name: Home
    protocol: http
    host: !secret home_nvr_ip
    port: 80
    user: !secret nvr_username
    password: !secret nvr_passsword
    events: [CrossLineDetection,CrossRegionDetection,LeftDetection,TakenAwayDetection,FaceDetection,AudioMutation,AudioAnomaly]
    channels: [1,2,3,4]
    
automation:
#
  - alias: 'Dahua camera event'
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: dahua_event_received
        event_data:
          code: VideoMotion
          action: Start
    action:
      - service: notify.html5
        data_template:
          title: "Camera Event"
          message: "Movement detected at {{ trigger.event.data.channel_name }}"
